<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-50MLDDI" failures="1" tests="8" name="selenium.tests.RegistrationInvalidBusiness" time="7.751" errors="0" timestamp="2023-01-09T17:24:26 MEZ" skipped="0">
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="tabTest" time="0.308"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailCommonPassword" time="2.172"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailWrongFormat2" time="1.100"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailWrongFormat" time="1.081"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="titleHeadline" time="0.305"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailName" time="0.912">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at selenium.tests.RegistrationInvalidBusiness.registrationFailName(RegistrationInvalidBusiness.java:45)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- registrationFailName -->
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailPassword" time="0.956"/>
  <testcase classname="selenium.tests.RegistrationInvalidBusiness" name="registrationFailEmail" time="0.917"/>
</testsuite> <!-- selenium.tests.RegistrationInvalidBusiness -->
